# Generated by Django 4.2.27 on 2026-01-15 01:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('SOLD', 'Sold')], default='LIVE', max_length=20)),
                ('stripe_payment_link_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_link_url', models.URLField(blank=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/', validators=[store.validators.validate_image_file_type, store.validators.validate_image_file_size])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.item')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', '-created_at'], name='store_item_status_c6b09e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['slug'], name='store_item_slug_8f3653_idx'),
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['item', 'sort_order'], name='store_itemi_item_id_c8add7_idx'),
        ),
    ]
